<?php

// Testimonials
define('TESTIMONIALS', [
    [
        'quote' => 'Loved my first suit so much, I decided to go and get a second one. Typically, when expectations are so high because of your first experience. Keep up the excellent work, gents!',
        'author' => 'Michael Brilla'
    ],
    [
        'quote' => 'My dream custom suit came through. I can\'t thank you enough for my custom-made suit\'s excellent customer service and fantastic fit. Thank you.',
        'author' => 'John Carlos'
    ],
    [
        'quote' => 'Absolutely impeccable craftsmanship. The attention to detail in every stitch is remarkable. This is what bespoke truly means.',
        'author' => 'James Hartford'
    ]
]);

// Process Steps
define('PROCESS_STEPS', [
    [
        'title' => 'UNDERSTANDING & REQUIREMENT MAPPING',
        'description' => 'We begin by understanding your vision, space, and functional needs to define a personalized design direction.'
    ],
    [
        'title' => 'SITE MEASUREMENT',
        'description' => 'Precise on-site measurements ensure accuracy and seamless integration with your space.'
    ],
    [
        'title' => 'MATERIAL, COLOUR & FINISH SELECTION',
        'description' => 'Curated mood boards guide the selection of colours, textures, and finishes to achieve depth and luxury.'
    ],
    [
        'title' => '3D DESIGN & APPROVAL',
        'description' => 'We present detailed drawings and 3D visualizations for your approval before moving ahead.'
    ],
    [
        'title' => 'PRODUCTION & CRAFTING',
        'description' => 'Expert craftsmanship and advanced techniques bring your design to life with exceptional quality.'
    ],
    [
        'title' => 'QUALITY CHECK & PRE-INSTALLATION',
        'description' => 'Each element undergoes strict quality checks to ensure perfection before dispatch.'
    ],
    [
        'title' => 'INSTALLATION & FINAL STYLING',
        'description' => 'We execute precise installation and finishing touches to deliver a flawless space.'
    ]
]);

// Instagram Posts
define('INSTAGRAM_POSTS', [
    [
        'image' => 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop',
        'link' => '#'
    ],
    [
        'image' => 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1200&auto=format&fit=crop',
        'link' => '#'
    ],
    [
        'image' => 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1200&auto=format&fit=crop',
        'link' => '#'
    ]
]);

// Semi-Precious Stones Images
define('SEMI_PRECIOUS_STONES', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// Accessory Images
define('ACCESSORIES', [
    'images/accessories/ChatGPT Image Apr 15, 2026, 10_00_36 PM.png',
    'images/accessories/for website (4).png',
    'images/accessories/for website (5).png',
    'images/accessories/for website (6).png',
    'images/accessories/images (3).jpg',
    'images/accessories/images (3).png',
    'images/accessories/images for website (8).png',
    'images/accessories/stone images (1).png',
    'images/accessories/stone images (2).png',
]);

// Article in Precious Stones Images
define('ARTICLES_IN_PRECIOUS_STONES', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// CNC Carving Panels Images
define('CNC_CARVING_PANELS', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// Furniture in Marble Images
define('FURNITURE_IN_MARBLE', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// Inlay Images
define('INLAY', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// Italian Glass Images
define('ITALIAN_GLASS', [

]);

// Metal with Precious Stones Images
define('METAL_WITH_PRECIOUS_STONES', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// Semi-Precious Slabs Images
define('SEMI_PRECIOUS_SLABS', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);

// Waterjet Floorings Images
define('WATERJET_FLOORINGS', [
    'images/gallery/Semi Precious Stone (1).png',
    'images/gallery/Semi Precious Stone (2).png',
    'images/gallery/Semi Precious Stone (3).png',
    'images/gallery/Semi Precious Stone (4).png',
    'images/gallery/Semi Precious Stone (5).png',
    'images/gallery/Semi Precious Stone (6).png',
    'images/gallery/Semi Precious Stone (7).png',
    'images/gallery/Semi Precious Stone (8).png',
    'images/gallery/Semi Precious Stone (9).png',
    'images/gallery/Semi Precious Stone (10).png',
    'images/gallery/Semi Precious Stone (11).png',
    'images/gallery/Semi Precious Stone (12).png',
    'images/gallery/Semi Precious Stone (13).png',
    'images/gallery/Semi Precious Stone (14).png',
    'images/gallery/Semi Precious Stone (15).png',
    'images/gallery/Semi Precious Stone (16).png',
    'images/gallery/Semi Precious Stone (17).png',
    'images/gallery/Semi Precious Stone (18).png',
    'images/gallery/Semi Precious Stone (19).png',
    'images/gallery/Semi Precious Stone (20).png',
    'images/gallery/Semi Precious Stone (21).png',
    'images/gallery/Semi Precious Stone (22).png',
    'images/gallery/Semi Precious Stone (23).png',
    'images/gallery/Semi Precious Stone (24).png',
    'images/gallery/Semi Precious Stone (25).png',
    'images/gallery/Semi Precious Stone (26).png',
    'images/gallery/Semi Precious Stone (27).png',
    'images/gallery/Semi Precious Stone (28).png',
    'images/gallery/Semi Precious Stone (29).png',
    'images/gallery/Semi Precious Stone (30).png',
    'images/gallery/Semi Precious Stone (31).png',
    'images/gallery/Semi Precious Stone (32).png',
    'images/gallery/Semi Precious Stone (33).png',
    'images/gallery/Semi Precious Stone (34).png',
    'images/gallery/Semi Precious Stone (35).png',
    'images/gallery/Semi Precious Stone (36).png',
    'images/gallery/Semi Precious Stone (37).png',
    'images/gallery/Semi Precious Stone (38).png',
    'images/gallery/Semi Precious Stone (39).png',
    'images/gallery/Semi Precious Stone (40).png',
    'images/gallery/Semi Precious Stone (44).png',
    'images/gallery/Semi Precious Stone (45).png',
    'images/gallery/Semi Precious Stone (46).png',
    'images/gallery/Semi Precious Stone (47).png',
    'images/gallery/Semi Precious Stone (48).png',
    'images/gallery/Semi Precious Stone (49).png',
    'images/gallery/Semi Precious Stone (50).png',
    'images/gallery/Semi Precious Stone (51).png',
    'images/gallery/Semi Precious Stone (52).png',
    'images/gallery/Semi Precious Stone (53).png',
    'images/gallery/Semi Precious Stone (54).png',
    'images/gallery/Semi Precious Stone (55).png',
    'images/gallery/Semi Precious Stone (56).png',
    'images/gallery/Semi Precious Stone (57).png',
    'images/gallery/Semi Precious Stone (58).png',
    'images/gallery/Semi Precious Stone (59).png',
    'images/gallery/Semi Precious Stone (60).png',
    'images/gallery/Semi Precious Stone (61).png',
    'images/gallery/Semi Precious Stone (62).png',
    'images/gallery/Semi Precious Stone (63).png',
    'images/gallery/Semi Precious Stone (64).png',
    'images/gallery/Semi Precious Stone (65).png',
    'images/gallery/Semi Precious Stone (66).png',
    'images/gallery/Semi Precious Stone (67).png',
    'images/gallery/Semi Precious Stone (68).png',
    'images/gallery/Semi Precious Stone (69).png',
]);
